# Generated by Django 3.0.6 on 2020-10-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mybooks", "0008_auto_20200629_0715"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookStat",
            fields=[
                (
                    "book_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mybooks.Book",
                    ),
                ),
            ],
            bases=("mybooks.book",),
        ),
    ]
