// eslint-disable-next-line
export const CREATE_BOOK = "CREATE_BOOK";
export const CREATE_BOOK_SUBMITTED = "CREATE_BOOK_SUBMITTED";
export const GET_BOOK_DETAIL = "RETRIEVE_BOOK_DETAIL";
export const GET_BOOK_LIST = "RETRIEVE_BOOK_LIST";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const UPDATE_BOOK_SUBMITTED = "UPDATE_BOOK_SUBMITTED";
export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_BOOK_SUBMITTED = "DELETE_BOOK_SUBMITTED";