# Generated by Django 3.0.6 on 2020-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0002_auto_20200625_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='wordcount',
            field=models.IntegerField(help_text='Your current word count', null=True, verbose_name='Word count'),
        ),
    ]
