# Generated by Django 3.0.6 on 2020-06-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0002_auto_20200614_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_finished',
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(help_text="What's it about?", null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='wordcount',
            field=models.IntegerField(help_text='Your word count when you added this title', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(help_text='Any good so far?', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default=1, help_text='A working title is great!', max_length=10, null=True),
        ),
    ]
