# Generated by Django 3.0.6 on 2020-06-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0003_auto_20200614_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='A working title is great!', max_length=10, null=True),
        ),
    ]
