# Generated by Django 3.0.6 on 2020-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0004_auto_20200614_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='goalwordcount',
            field=models.IntegerField(null=True),
        ),
    ]
