# Generated by Django 3.0.6 on 2020-06-27 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mybooks", "0004_auto_20200625_2019"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
