# Generated by Django 3.0.6 on 2020-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0006_book_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='A working title is great!', max_length=50, null=True),
        ),
    ]
