# Generated by Django 3.2.3 on 2021-08-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0011_auto_20201222_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='author',
        ),
    ]
